# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=11)),
                ('grade', models.CharField(choices=[('BPO1', 'BPO1'), ('BPO2', 'BPO2'), ('BPO3', 'BPO3'), ('BPO4', 'BPO4'), ('BPO5', 'BPO5'), ('BPO6', 'BPO6'), ('BPO7', 'BPO7'), ('BPO8', 'BPO8'), ('Y', 'Y'), ('C1Y', 'C1Y'), ('C1', 'C1'), ('C2', 'C2'), ('C3A', 'C3A'), ('C3B', 'C3B'), ('C4', 'C4'), ('C5', 'C5')], max_length=4)),
                ('location', models.CharField(choices=[('SH', 'Shanghai'), ('HZ', 'Hangzhou'), ('TJ', 'Tianjian'), ('DL', 'Dalian'), ('BJ', 'Beijing'), ('SZ', 'Shenzhen')], max_length=2)),
                ('additional_location', models.CharField(max_length=200)),
                ('probation', models.CharField(choices=[('0', 'No Probation'), ('3', '3 Month Probation'), ('6', '6 Month Probation')], max_length=1)),
                ('salary', models.IntegerField()),
                ('var_pay', models.IntegerField()),
                ('offer_date', models.DateField()),
            ],
        ),
    ]
