# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 05:35
from __future__ import unicode_literals

import offer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_auto_20160813_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='offer_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='additional_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='location',
            field=models.CharField(choices=[('SH', 'Shanghai'), ('HZ', 'Hangzhou'), ('TJ', 'Tianjian'), ('DL', 'Dalian'), ('BJ', 'Beijing'), ('SZ', 'Shenzhen')], default='SH', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='mobile',
            field=models.CharField(max_length=11, validators=[offer.models.Candidate.validate_mobile]),
        ),
    ]
