# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_auto_20160813_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(default='wenkai.gu@tcs.com', max_length=254),
            preserve_default=False,
        ),
    ]
