# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_candidate_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='offer_date',
            field=models.DateField(blank=True, default=''),
        ),
    ]
