# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_auto_20160813_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='offer_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
