# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 13:31
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer', '0007_auto_20160813_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='account',
            field=models.CharField(default='Cisco', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='recruiter',
            field=models.ForeignKey(default=922901, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
