# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0009_candidate_offer_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='offer_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
