# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_auto_20160820_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='offer_path',
            field=models.FilePathField(blank=True, default=None, null=True),
        ),
    ]
