# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_candidate_offer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='offer_path',
        ),
    ]
